# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - linters
  - unit-tests

check:
  stage: linters
  image: python:3.6
  allow_failure: yes
  only:
    - dev
    - web
  before_script:
    - pip install flake8 isort mypy
  script:
    - make check

unit-tests:
  stage: unit-tests
  image: python:3.6
  only:
    - dev
    - web
  before_script:
    - apt update
    - apt install -y graphviz
    - pip install pipenv
    - pipenv sync -d
    - pipenv run make protos
  script:
    - pipenv run make tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
