# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
    - linters
    - unit-tests

pep8:
    stage: linters
    allow_failure: yes
    only:
        - dev
    before_script:
        - pip install flake8
    script:
        - flake8 hathor/ tests/ *.py

unit-tests:
    stage: unit-tests
    only:
        - dev
    before_script:
        - pip install -r requirements.txt
    script:
        - nosetests --with-coverage --cover-package=hathor --cover-html
