# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
    - linters
    - unittests

pep8:
    - stage: linters
    - only: dev
    - allow_failure: yes
    - before_script:
        pip install flake8
    - script:
        flake8 hathor/ tests/ *.py

unittests:
    - stage: unittests
    - only: dev
    - before_script:
        pip install -r requirements.txt
    - script:
        nosetests --with-coverage --cover-package=hathor --cover-html
